### ISSUE TITLE
Doesn't work in laravel 4

### ISSUE THREAD

**Issue by frankysoputra** [skmetaly/laravel-smtp-email-verifier#1]
i had try to require this package in laravel 4, but i doesn't work.

"Could not find package skmetaly/laravel-smtp-email-verifier at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability"

please fix it. at least please more documentation about minimum stability. and what version of laravel can use it.

**Comment by skmetaly** [comment]
Hi, 

For now, at least temporarily go to composer.json file and change minimum stability to : 

``` json
  "minimum-stability": "dev"
```

and redo a 

``` bash
composer install
```
