### ISSUE TITLE
Class not found: `Socket\Raw\Exception`

### ISSUE THREAD

**Issue by sjamaan** [skmetaly/laravel-smtp-email-verifier#2]
It seems that this library has an implicit dependency on [php-socket-raw](https://github.com/clue/php-socket-raw/blob/master/src/Exception.php); I got an error about the class `Socket\Raw\Exception` not existing.

This exception class is [used by `SocketStream`](https://github.com/skmetaly/laravel-smtp-email-verifier/blob/master/src/Socket/SocketStream.php#L7) and [raised when reading from the socket fails](https://github.com/skmetaly/laravel-smtp-email-verifier/blob/master/src/Socket/SocketStream.php#L141)

**Comment by skmetaly** [comment]
Thanks @sjamaan for raising this ! Not sure why i never noticed this.

**Comment by sjamaan** [comment]
Thanks @skmetaly!  Maybe now is also a good moment to tag a 1.0 version? I'm currently using `dev-master` in my project, but it would be nice if I could rely on a stable, unchanging version.

**Comment by skmetaly** [comment]
yup. I was thinking about that but planned to do it in the evening + some other cleaning of it . Tagged it now to 1.0.0 what is currently on master, and do the cleaning later

**Comment by sjamaan** [comment]
Wow, now that's what I call a quick response :)

**Comment by sjamaan** [comment]
hm, it looks like 1.0.0 doesn't point at the latest commit but an old one!

**Comment by skmetaly** [comment]
Sorry. Tagged without pulling. I retagged now. to latest commit. Let me know if you have any issues
